version: '3.4'

services:
  foralending.api:
    image: ${DOCKER_REGISTRY-}foralendingapi
    build:
      context: .
      dockerfile: ForaLending.API/Dockerfile
    ports:
      - "5001:5001"
      - "5000:5000"
    depends_on:
     - "app_db"

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ForaDb
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data


volumes:
  app_data:
